### ISSUE TITLE
Proposal: Improve printing

### ISSUE THREAD

**Issue by dzvancuks** [wmnsk/go-gtp#184]
Currently when I try to print Message output is Header + Payload in hex:
```
{Flags: 0x32, Type: 0x10, Length: 57, TEID: 0x00000000, SequenceNumber: 0x01c8, Payload: []byte{0x2, 0x21, 0x43, 0x65, 0x87, 0x9, 0x21, 0x43, 0xf5, 0xe, 0x8, 0x10, 0x0, 0x2, 0x34, 0x56, 0x11, 0x0, 0x2, 0x34, 0x56, 0x14, 0x5, 0x83, 0x0, 0xd, 0x3, 0x69, 0x6f, 0x74, 0x4, 0x31, 0x6e, 0x63, 0x65, 0x3, 0x63, 0x6f, 0x6d, 0x85, 0x0, 0x4, 0xc0, 0xa8, 0x1, 0x1, 0x85, 0x0, 0x4, 0xa, 0xa, 0x2, 0x2}}
```
This is due to the fact that only header has String() interface: `func (h *Header) String() string`

For debugging purposes I'd suggest to have an option to print fully parsed message. Where instead of payload I could see IMSI, TEID, etc fields in readable format.

**Comment by wmnsk** [comment]
That definitely makes sense. Do you have any idea on how we implement it?

**Comment by wmnsk** [comment]
I was thinking about this for a while. The easiest solution may be to introduce the `reflect` package but I don’t want to do that because it may have serious impacts on the performance, and, moreover, it increases the complexity to the source code too much. The second option I came up with is implementing more glandular method on each message, which is super cumbersome (I would use my time for more productive work instead).

Since basically all the fields are exported, I think the most realistic solution is to write users own printer only for the messages they really use.
I’m closing this issue, but let me know if someone reading this has any idea. I’m still up for further discussion.
