### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by 2-face** [wmnsk/go-gtp#29]
A config file should be possible to use that would define exact content of each message. Otherwise each message has to be compose programatically and code needs to be rebuilt.

**Comment by wmnsk** [comment]
Thank you for nice idea. I agree some config help users to handle values easier, and it may be implemented in the future, but currently this project has only low-level implementations & a few helpers that “protocol stack” requires, and is targeting those who write programs by their own because;

* some values should inevitably be set dynamically(=in a programmable way), and defining a single-formatted config makes the package less flexible.
* this is a _package_ to implement nodes by developers own, not a _independent software_.

However, if you need, it is possible to define original one, for example by adding a `config` struct and put tags on it, and put values to each field in your own program. I’ll be happy to help you if you try that.

**Comment by 2-face** [comment]
Sure understood. Just an idea, I think I've seen somewhere on github some other telco related project where signalling messages content was defined in asn.1.

If time allows I would like to develop sth around mme/sgsn with your library.

**Comment by wmnsk** [comment]
Thank you for understanding.
I’ll keep on trying hard to make it ready for high-level implementations some day.

I hope you’ll have time to develop MME/SGSN and send a PR with example :smiley:

**Comment by wmnsk** [comment]
Let me know if you have anything to discuss further. Thanks.
